version: '3'

services:

  db-story:
    image: mongo
    volumes:
      - mongostory:/data/db
    restart: unless-stopped
    container_name: story-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      
  story-service:
    image: story-service
    build: ./story-service
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db-story
      DB_DROP: 'false'
      REGISTRY_HOST: eureka-service
      REGISTRY_PORT: 8761
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: root
      RABBIT_MQ_PASSWORD: root
      JAEGER_SERVICE_NAME: story_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: unless-stopped
    container_name: story-service
    ports:
      - 8084:8084
      
  db-media:
    image: mongo
    volumes:
      - mongomedia:/data/db
    restart: unless-stopped
    container_name: media-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      
  media-service:
    image: media-service
    volumes:
      - mongofiles:/home/app/uploads
    build: ./media-service
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db-media
      DB_DROP: 'false'
      REGISTRY_HOST: eureka-service
      REGISTRY_PORT: 8761
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: root
      RABBIT_MQ_PASSWORD: root
      JAEGER_SERVICE_NAME: media_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: unless-stopped
    container_name: media-service
    ports:
      - 8085:8085
      
  db-auth:
    image: postgres
    restart: unless-stopped
    container_name: auth-db
    volumes:
      - postgresauth:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: users
      
  auth-service:
    image: auth-service
    build: ./auth-service
    environment:
      DB_USER: root
      DB_PASS: root
      DB_AUTO_DDL: update
      DB_PATH: jdbc:postgresql://db-auth:5432/users
      REGISTRY_HOST: eureka-service
      REGISTRY_PORT: 8761
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: root
      RABBIT_MQ_PASSWORD: root
      JAEGER_SERVICE_NAME: auth_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: unless-stopped
    container_name: auth-service
    ports:
      - 8081:8081
      
  db-publishing:
    image: postgres
    restart: unless-stopped
    container_name: publishing-db
    volumes:
      - postgrespublishing:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: publishing
      
  publishing-service:
    image: publishing-service
    build: ./publishing-service
    environment:
      DB_USER: root
      DB_PASS: root
      DB_AUTO_DDL: update
      DB_PATH: jdbc:postgresql://db-publishing:5432/publishing
      REGISTRY_HOST: eureka-service
      REGISTRY_PORT: 8761
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: root
      RABBIT_MQ_PASSWORD: root
      JAEGER_SERVICE_NAME: publishing_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: unless-stopped
    container_name: publishing-service
    ports:
      - 8083:8083
      
  dbfollow:
    image: neo4j
    restart: unless-stopped
    container_name: following-db
    volumes:
      - neo4jfollow:/data
    environment:
      NEO4J_AUTH: neo4j/root
      
  following-service:
    image: following-service
    build: ./following-service
    environment:
      DB_USER: neo4j
      DB_PASS: root
      DB_PATH: neo4j://dbfollow:7687
      REGISTRY_HOST: eureka-service
      REGISTRY_PORT: 8761
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: root
      RABBIT_MQ_PASSWORD: root
      JAEGER_SERVICE_NAME: following_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: unless-stopped
    container_name: following-service
    ports:
      - 8082:8082
      
  db-activity:
    image: postgres
    restart: unless-stopped
    container_name: activity-db
    volumes:
      - postgresactivity:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: activity
      
  activity-service:
    image: activity-service
    build: ./activity-service
    environment:
      DB_USER: root
      DB_PASS: root
      DB_AUTO_DDL: update
      DB_PATH: jdbc:postgresql://db-activity:5432/activity
      REGISTRY_HOST: eureka-service
      REGISTRY_PORT: 8761
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: root
      RABBIT_MQ_PASSWORD: root
      JAEGER_SERVICE_NAME: activity_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: unless-stopped
    container_name: activity-service
    ports:
      - 8086:8086

  db-notification:
    image: mongo
    volumes:
      - mongonotification:/data/db
    restart: unless-stopped
    container_name: notification-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  notification-service:
    image: notification-service
    build: ./notification-service
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db-notification
      DB_DROP: 'false'
      REGISTRY_HOST: eureka-service
      REGISTRY_PORT: 8761
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: root
      RABBIT_MQ_PASSWORD: root
      JAEGER_SERVICE_NAME: notification_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: unless-stopped
    container_name: notification-service
    ports:
      - 8090:8090

  db-campaign:
    image: postgres
    restart: unless-stopped
    container_name: campaign-db
    volumes:
      - postgrescampaign:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: campaign
      
  campaign-service:
    image: campaign-service
    build: ./campaign-service
    environment:
      DB_USER: root
      DB_PASS: root
      DB_AUTO_DDL: update
      DB_PATH: jdbc:postgresql://db-campaign:5432/campaign
      REGISTRY_HOST: eureka-service
      REGISTRY_PORT: 8761
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USERNAME: root
      RABBIT_MQ_PASSWORD: root
      JAEGER_SERVICE_NAME: campaign_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: unless-stopped
    container_name: campaign-service
    ports:
      - 8087:8087

  db-agent:
    image: postgres
    restart: unless-stopped
    container_name: agent-db
    volumes:
      - postgresagent:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: agent_app
      
  agent-service:
    image: agent-service
    build: ../agent-app
    environment:
      DB_USER: root
      DB_PASS: root
      DB_AUTO_DDL: update
      DB_PATH: jdbc:postgresql://db-agent:5432/agent_app
      ACTIVITY_HOST: activity-service
      CAMPAIGN_HOST: campaign-service
      AUTH_HOST: auth-service
      MEDIA_HOST: media-service
      REPORT_HOST: report-service
      JAEGER_SERVICE_NAME: agent_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    restart: unless-stopped
    container_name: agent-service
    ports:
      - 8091:8091

  db-report:
    image: existdb-custom
    build: ../existdb
    restart: unless-stopped
    container_name: report-db
    volumes:
      - existreportconfig:/config
      - existreportdata:/data

  report-service:
    image: report-service
    build: ../report
    environment:
      DB_USER: admin
      DB_PASS: 123
      DB_URI: xmldb:exist://db-report:8080/exist/xmlrpc
      DB_HOST: db-report
      DB_PORT: 8080
      ACTIVITY_HOST: activity-service
      CAMPAIGN_HOST: campaign-service
    restart: unless-stopped
    container_name: report-service
    ports:
      - 8092:8092

  eureka-service:
    image: eureka-service
    container_name: eureka-service
    build: ../eureka-server
    restart: unless-stopped
    ports:
      - 8761:8761
         
  zuul:
    image: zuul
    container_name: zuul
    build: ../zuul-server
    restart: unless-stopped
    environment:
      REGISTRY_HOST: eureka-service
      REGISTRY_PORT: 8761
      AUTH_HOST: auth-service
      FOLLOWING_HOST: following-service
      PUBLISHING_HOST: publishing-service
      STORY_HOST: story-service
      MEDIA_HOST: media-service
      ACTIVITY_HOST: activity-service
      NOTIFICATION_HOST: notification-service
      CAMPAIGN_HOST: campaign-service
      JAEGER_SERVICE_NAME: zuul_service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831     
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    ports:
      - 8111:8111
  
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8.16'
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_USERNAME: root
      RABBITMQ_PASSWORD: root

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      
volumes:
  mongostory:
  mongomedia:
  mongofiles:
  postgresauth:
  postgrespublishing:
  neo4jfollow:
  postgresactivity:
  mongonotification:
  postgrescampaign:
  postgresagent:
  existreportconfig:
  existreportdata: